# Generated by Django 4.1 on 2022-12-22 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engine_base_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alarm_datetime', models.DateTimeField(default=datetime.date(1900, 1, 1), verbose_name='last_alarm_time')),
                ('next_repair_date', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='next_repair_time')),
            ],
        ),
    ]
